"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: Unreal.Actor
  IDL file: ActorState.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import Unreal

if TYPE_CHECKING:
    import Unreal.Math



@dataclass
@annotate.final
@annotate.autoid("sequential")
class ActorState(idl.IdlStruct, typename="Unreal.Actor.ActorState"):
    Name: str
    Id: str
    Transform: 'Unreal.Math.Transform'


