/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Actors/ActorState.c
  Source: C:\Dev\IDLCompilerV2\Unreal\Actors\ActorState.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "ActorState.h"

static const uint32_t Unreal_Actor_ActorState_ops [] =
{
  /* ActorState */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (Unreal_Actor_ActorState, Name),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (Unreal_Actor_ActorState, Id),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Actor_ActorState, Transform), (3u << 16u) + 4u /* Transform */,
  DDS_OP_RTS,

  /* Transform */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Rotation), (3u << 16u) + 10u /* Quaternion */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Scale3D), (3u << 16u) + 16u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Translation), (3u << 16u) + 13u /* Vector3 */,
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, W),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Z),
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Actor_ActorState_desc =
{
  .m_size = sizeof (Unreal_Actor_ActorState),
  .m_align = dds_alignof (Unreal_Actor_ActorState),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Actor::ActorState",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = Unreal_Actor_ActorState_ops,
  .m_meta = ""
};

