/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Actors/ActorState.h
  Source: C:\Dev\IDLCompilerV2\Unreal\Actors\ActorState.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_ACTORS_ACTORSTATE_H_158BD43CEE1FF20ECCE4C27A427BA551
#define DDSC_C__DEV_DATATYPES_COMPILED_ACTORS_ACTORSTATE_H_158BD43CEE1FF20ECCE4C27A427BA551

#include "CycloneImpl/Math/Geometry.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Unreal_Actor_ActorState
{
  char * Name;
  char * Id;
  struct Unreal_Math_Transform Transform;
} Unreal_Actor_ActorState;

extern const dds_topic_descriptor_t Unreal_Actor_ActorState_desc;

#define Unreal_Actor_ActorState__alloc() \
((Unreal_Actor_ActorState*) dds_alloc (sizeof (Unreal_Actor_ActorState)));

#define Unreal_Actor_ActorState_free(d,o) \
dds_sample_free ((d), &Unreal_Actor_ActorState_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_ACTORS_ACTORSTATE_H_158BD43CEE1FF20ECCE4C27A427BA551 */
