/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/BoundedArrayPrimitives.c
  Source: C:\Dev\DataTypes\ROS\test_msgs\msg\BoundedArrayPrimitives.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "BoundedArrayPrimitives.h"

static const uint32_t test_msgs_msg_BoundedArrayPrimitives_ops [] =
{
  /* BoundedArrayPrimitives */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_BLN, offsetof (test_msgs_msg_BoundedArrayPrimitives, bool_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, byte_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_1BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_BoundedArrayPrimitives, char_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (test_msgs_msg_BoundedArrayPrimitives, float32_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (test_msgs_msg_BoundedArrayPrimitives, float64_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, int8_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, uint8_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_2BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_BoundedArrayPrimitives, int16_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_2BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, uint16_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_BoundedArrayPrimitives, int32_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_4BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, uint32_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_BoundedArrayPrimitives, int64_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_8BY, offsetof (test_msgs_msg_BoundedArrayPrimitives, uint64_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_BSQ | DDS_OP_SUBTYPE_STR, offsetof (test_msgs_msg_BoundedArrayPrimitives, string_values), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_BoundedArrayPrimitives, check),
  DDS_OP_RTS
};

const dds_topic_descriptor_t test_msgs_msg_BoundedArrayPrimitives_desc =
{
  .m_size = sizeof (test_msgs_msg_BoundedArrayPrimitives),
  .m_align = dds_alignof (test_msgs_msg_BoundedArrayPrimitives),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "test_msgs::msg::BoundedArrayPrimitives",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = test_msgs_msg_BoundedArrayPrimitives_ops,
  .m_meta = ""
};

