/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/DynamicArrayNested.h
  Source: C:\Dev\DataTypes\ROS\test_msgs\msg\DynamicArrayNested.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_MSG_DYNAMICARRAYNESTED_H_A59BC4719FA393A68FDA1E3C6640D421
#define DDSC_C__DEV_DATATYPES_COMPILED_MSG_DYNAMICARRAYNESTED_H_A59BC4719FA393A68FDA1E3C6640D421

#include "Primitives.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_TEST_MSGS_MSG_PRIMITIVES_DEFINED
#define DDS_SEQUENCE_TEST_MSGS_MSG_PRIMITIVES_DEFINED
typedef struct dds_sequence_test_msgs_msg_Primitives
{
  uint32_t _maximum;
  uint32_t _length;
  struct test_msgs_msg_Primitives *_buffer;
  bool _release;
} dds_sequence_test_msgs_msg_Primitives;

#define dds_sequence_test_msgs_msg_Primitives__alloc() \
((dds_sequence_test_msgs_msg_Primitives*) dds_alloc (sizeof (dds_sequence_test_msgs_msg_Primitives)));

#define dds_sequence_test_msgs_msg_Primitives_allocbuf(l) \
((struct test_msgs_msg_Primitives *) dds_alloc ((l) * sizeof (struct test_msgs_msg_Primitives)))
#endif /* DDS_SEQUENCE_TEST_MSGS_MSG_PRIMITIVES_DEFINED */

typedef struct test_msgs_msg_DynamicArrayNested
{
  dds_sequence_test_msgs_msg_Primitives primitive_values;
} test_msgs_msg_DynamicArrayNested;

extern const dds_topic_descriptor_t test_msgs_msg_DynamicArrayNested_desc;

#define test_msgs_msg_DynamicArrayNested__alloc() \
((test_msgs_msg_DynamicArrayNested*) dds_alloc (sizeof (test_msgs_msg_DynamicArrayNested)));

#define test_msgs_msg_DynamicArrayNested_free(d,o) \
dds_sample_free ((d), &test_msgs_msg_DynamicArrayNested_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_MSG_DYNAMICARRAYNESTED_H_A59BC4719FA393A68FDA1E3C6640D421 */
