/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/DynamicArrayPrimitives.c
  Source: C:\Dev\DataTypes\ROS\test_msgs\msg\DynamicArrayPrimitives.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "DynamicArrayPrimitives.h"

static const uint32_t test_msgs_msg_DynamicArrayPrimitives_ops [] =
{
  /* DynamicArrayPrimitives */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_BLN, offsetof (test_msgs_msg_DynamicArrayPrimitives, bool_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, byte_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_DynamicArrayPrimitives, char_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (test_msgs_msg_DynamicArrayPrimitives, float32_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (test_msgs_msg_DynamicArrayPrimitives, float64_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, int8_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, uint8_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_2BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_DynamicArrayPrimitives, int16_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_2BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, uint16_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_DynamicArrayPrimitives, int32_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, uint32_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_DynamicArrayPrimitives, int64_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY, offsetof (test_msgs_msg_DynamicArrayPrimitives, uint64_values),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STR, offsetof (test_msgs_msg_DynamicArrayPrimitives, string_values),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (test_msgs_msg_DynamicArrayPrimitives, check),
  DDS_OP_RTS
};

const dds_topic_descriptor_t test_msgs_msg_DynamicArrayPrimitives_desc =
{
  .m_size = sizeof (test_msgs_msg_DynamicArrayPrimitives),
  .m_align = dds_alignof (test_msgs_msg_DynamicArrayPrimitives),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "test_msgs::msg::DynamicArrayPrimitives",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = test_msgs_msg_DynamicArrayPrimitives_ops,
  .m_meta = ""
};

