/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/Nested.h
  Source: C:\Dev\DataTypes\ROS\test_msgs\msg\Nested.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_MSG_NESTED_H_5424197FE85132A01E2DB98AD076936D
#define DDSC_C__DEV_DATATYPES_COMPILED_MSG_NESTED_H_5424197FE85132A01E2DB98AD076936D

#include "Primitives.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct test_msgs_msg_Nested
{
  struct test_msgs_msg_Primitives primitive_values;
} test_msgs_msg_Nested;

extern const dds_topic_descriptor_t test_msgs_msg_Nested_desc;

#define test_msgs_msg_Nested__alloc() \
((test_msgs_msg_Nested*) dds_alloc (sizeof (test_msgs_msg_Nested)));

#define test_msgs_msg_Nested_free(d,o) \
dds_sample_free ((d), &test_msgs_msg_Nested_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_MSG_NESTED_H_5424197FE85132A01E2DB98AD076936D */
