/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/Primitives.h
  Source: C:\Dev\DataTypes\ROS\test_msgs\msg\Primitives.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_MSG_PRIMITIVES_H_06B7FE11713897A42D52C44D65F0CE58
#define DDSC_C__DEV_DATATYPES_COMPILED_MSG_PRIMITIVES_H_06B7FE11713897A42D52C44D65F0CE58

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct test_msgs_msg_Primitives
{
  bool bool_value;
  uint8_t byte_value;
  char char_value;
  float float32_value;
  double float64_value;
  uint8_t int8_value;
  uint8_t uint8_value;
  int16_t int16_value;
  uint16_t uint16_value;
  int32_t int32_value;
  uint32_t uint32_value;
  int64_t int64_value;
  uint64_t uint64_value;
  char * string_value;
} test_msgs_msg_Primitives;

extern const dds_topic_descriptor_t test_msgs_msg_Primitives_desc;

#define test_msgs_msg_Primitives__alloc() \
((test_msgs_msg_Primitives*) dds_alloc (sizeof (test_msgs_msg_Primitives)));

#define test_msgs_msg_Primitives_free(d,o) \
dds_sample_free ((d), &test_msgs_msg_Primitives_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_MSG_PRIMITIVES_H_06B7FE11713897A42D52C44D65F0CE58 */
