/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Math/Geometry.h
  Source: C:\Dev\IDLCompilerV2\Unreal\Math\Geometry.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_MATH_GEOMETRY_H_ECB925E2F0B9B3D7C412A22F1F80DE25
#define DDSC_C__DEV_DATATYPES_COMPILED_MATH_GEOMETRY_H_ECB925E2F0B9B3D7C412A22F1F80DE25

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Unreal_Math_Quaternion
{
  double W;
  double X;
  double Y;
  double Z;
} Unreal_Math_Quaternion;

extern const dds_topic_descriptor_t Unreal_Math_Quaternion_desc;

#define Unreal_Math_Quaternion__alloc() \
((Unreal_Math_Quaternion*) dds_alloc (sizeof (Unreal_Math_Quaternion)));

#define Unreal_Math_Quaternion_free(d,o) \
dds_sample_free ((d), &Unreal_Math_Quaternion_desc, (o))

typedef struct Unreal_Math_Vector3
{
  double X;
  double Y;
  double Z;
} Unreal_Math_Vector3;

extern const dds_topic_descriptor_t Unreal_Math_Vector3_desc;

#define Unreal_Math_Vector3__alloc() \
((Unreal_Math_Vector3*) dds_alloc (sizeof (Unreal_Math_Vector3)));

#define Unreal_Math_Vector3_free(d,o) \
dds_sample_free ((d), &Unreal_Math_Vector3_desc, (o))

typedef struct Unreal_Math_Accel
{
  struct Unreal_Math_Vector3 Linear;
  struct Unreal_Math_Vector3 Angular;
} Unreal_Math_Accel;

extern const dds_topic_descriptor_t Unreal_Math_Accel_desc;

#define Unreal_Math_Accel__alloc() \
((Unreal_Math_Accel*) dds_alloc (sizeof (Unreal_Math_Accel)));

#define Unreal_Math_Accel_free(d,o) \
dds_sample_free ((d), &Unreal_Math_Accel_desc, (o))

typedef struct Unreal_Math_Vector2D
{
  double X;
  double Y;
} Unreal_Math_Vector2D;

extern const dds_topic_descriptor_t Unreal_Math_Vector2D_desc;

#define Unreal_Math_Vector2D__alloc() \
((Unreal_Math_Vector2D*) dds_alloc (sizeof (Unreal_Math_Vector2D)));

#define Unreal_Math_Vector2D_free(d,o) \
dds_sample_free ((d), &Unreal_Math_Vector2D_desc, (o))

typedef struct Unreal_Math_Transform
{
  struct Unreal_Math_Quaternion Rotation;
  struct Unreal_Math_Vector3 Scale3D;
  struct Unreal_Math_Vector3 Translation;
} Unreal_Math_Transform;

extern const dds_topic_descriptor_t Unreal_Math_Transform_desc;

#define Unreal_Math_Transform__alloc() \
((Unreal_Math_Transform*) dds_alloc (sizeof (Unreal_Math_Transform)));

#define Unreal_Math_Transform_free(d,o) \
dds_sample_free ((d), &Unreal_Math_Transform_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_MATH_GEOMETRY_H_ECB925E2F0B9B3D7C412A22F1F80DE25 */
