/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Math/Geometry.c
  Source: C:\Dev\IDLCompilerV2\Unreal\Math\Geometry.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Geometry.h"

static const uint32_t Unreal_Math_Quaternion_ops [] =
{
  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, W),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Math_Quaternion_desc =
{
  .m_size = sizeof (Unreal_Math_Quaternion),
  .m_align = dds_alignof (Unreal_Math_Quaternion),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Math::Quaternion",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = Unreal_Math_Quaternion_ops,
  .m_meta = ""
};

static const uint32_t Unreal_Math_Vector3_ops [] =
{
  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Math_Vector3_desc =
{
  .m_size = sizeof (Unreal_Math_Vector3),
  .m_align = dds_alignof (Unreal_Math_Vector3),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Math::Vector3",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = Unreal_Math_Vector3_ops,
  .m_meta = ""
};

static const uint32_t Unreal_Math_Accel_ops [] =
{
  /* Accel */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Accel, Linear), (3u << 16u) + 7u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Accel, Angular), (3u << 16u) + 4u /* Vector3 */,
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Math_Accel_desc =
{
  .m_size = sizeof (Unreal_Math_Accel),
  .m_align = dds_alignof (Unreal_Math_Accel),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Math::Accel",
  .m_keys = NULL,
  .m_nops = 7,
  .m_ops = Unreal_Math_Accel_ops,
  .m_meta = ""
};

static const uint32_t Unreal_Math_Vector2D_ops [] =
{
  /* Vector2D */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector2D, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector2D, Y),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Math_Vector2D_desc =
{
  .m_size = sizeof (Unreal_Math_Vector2D),
  .m_align = dds_alignof (Unreal_Math_Vector2D),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Math::Vector2D",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = Unreal_Math_Vector2D_ops,
  .m_meta = ""
};

static const uint32_t Unreal_Math_Transform_ops [] =
{
  /* Transform */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Rotation), (3u << 16u) + 10u /* Quaternion */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Scale3D), (3u << 16u) + 16u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (Unreal_Math_Transform, Translation), (3u << 16u) + 13u /* Vector3 */,
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, W),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Quaternion, Z),
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Unreal_Math_Vector3, Z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Math_Transform_desc =
{
  .m_size = sizeof (Unreal_Math_Transform),
  .m_align = dds_alignof (Unreal_Math_Transform),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Math::Transform",
  .m_keys = NULL,
  .m_nops = 13,
  .m_ops = Unreal_Math_Transform_ops,
  .m_meta = ""
};

