/****************************************************************

Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Exemple/HelloWorld.c
  Source: C:\Dev\IDLCompilerV2\Unreal\Exemple\HelloWorld.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "HelloWorld.h"

static const uint32_t Unreal_Exemple_HelloWorld_ops [] =
{
  /* HelloWorld */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (Unreal_Exemple_HelloWorld, HelloStr),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (Unreal_Exemple_HelloWorld, HelloFloat),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unreal_Exemple_HelloWorld_desc =
{
  .m_size = sizeof (Unreal_Exemple_HelloWorld),
  .m_align = dds_alignof (Unreal_Exemple_HelloWorld),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "Unreal::Exemple::HelloWorld",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = Unreal_Exemple_HelloWorld_ops,
  .m_meta = ""
};



