/****************************************************************

Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/Exemple/HelloWorld.h
  Source: C:\Dev\IDLCompilerV2\Unreal\Exemple\HelloWorld.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_EXEMPLE_HELLOWORLD_H_C46184DA77DF968F12D25934E1492F25
#define DDSC_C__DEV_DATATYPES_COMPILED_EXEMPLE_HELLOWORLD_H_C46184DA77DF968F12D25934E1492F25

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

  typedef struct Unreal_Exemple_HelloWorld
  {
    char * HelloStr;
    float HelloFloat;
  } Unreal_Exemple_HelloWorld;

  extern const dds_topic_descriptor_t Unreal_Exemple_HelloWorld_desc;

#define Unreal_Exemple_HelloWorld__alloc() \
((Unreal_Exemple_HelloWorld*) dds_alloc (sizeof (Unreal_Exemple_HelloWorld)));

#define Unreal_Exemple_HelloWorld_free(d,o) \
dds_sample_free ((d), &Unreal_Exemple_HelloWorld_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_EXEMPLE_HELLOWORLD_H_C46184DA77DF968F12D25934E1492F25 */
