"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: Unreal.Exemple
  IDL file: HelloWorld.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import Unreal


@dataclass
@annotate.final
@annotate.autoid("sequential")
class HelloWorld(idl.IdlStruct, typename="Unreal.Exemple.HelloWorld"):
    HelloStr: str
    HelloFloat: types.float32


