/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   MRSActorState.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : MRSActorState.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/MRSConvertUtils.h"


#include "CycloneImpl/Actors/ActorState.h"

#include "MRSActorState.generated.h" 



USTRUCT(Blueprintable)
struct FMRSActorState
{
    GENERATED_BODY()

    FMRSActorState()
    {

    };

    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Id;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FTransform Transform;
    

    void DDSToUE(const Unreal_Actor_ActorState& InData);
    void UEToDDS(Unreal_Actor_ActorState& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FMRSActorStateCallback, const FMRSActorState, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEDATAMODEL_API UActorState_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FMRSActorStateCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FMRSActorState& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FMRSActorState Input);

private:
    Unreal_Actor_ActorState* Data;
};