"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: Unreal.Math
  IDL file: Geometry.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import Unreal


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Quaternion(idl.IdlStruct, typename="Unreal.Math.Quaternion"):
    W: types.float64
    X: types.float64
    Y: types.float64
    Z: types.float64


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Vector3(idl.IdlStruct, typename="Unreal.Math.Vector3"):
    X: types.float64
    Y: types.float64
    Z: types.float64


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Accel(idl.IdlStruct, typename="Unreal.Math.Accel"):
    Linear: 'Unreal.Math.Vector3'
    Angular: 'Unreal.Math.Vector3'


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Vector2D(idl.IdlStruct, typename="Unreal.Math.Vector2D"):
    X: types.float64
    Y: types.float64


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Transform(idl.IdlStruct, typename="Unreal.Math.Transform"):
    Rotation: 'Unreal.Math.Quaternion'
    Scale3D: 'Unreal.Math.Vector3'
    Translation: 'Unreal.Math.Vector3'


