/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSDynamicArrayNested.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSDynamicArrayNested.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/MRSConvertUtils.h"

#include "IDLPrimitives.h"

#include "DataImplementation/DynamicArrayNested.h"

#include "IDLDynamicArrayNested.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FIDLDynamicArrayNested
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FIDLDynamicArrayNested()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    TArray<FIDLPrimitives> PrimitiveValues;
    

    /**
     * @cond
     */
    void DDSToUE (const test_msgs_msg_DynamicArrayNested& InData) 
    {
        UMRSConvertUtils::SequenceToTArray<test_msgs_msg_Primitives, FIDLPrimitives>(InData.primitive_values._buffer, PrimitiveValues, InData.primitive_values._length);
    };

    void UEToDDS (test_msgs_msg_DynamicArrayNested& OutData) 
    {
        OutData.primitive_values._length = PrimitiveValues.Num();
        OutData.primitive_values._buffer = dds_sequence_test_msgs_msg_Primitives_allocbuf(PrimitiveValues.Num());
        OutData.primitive_values._release = true;
        UMRSConvertUtils::TArrayToSequence<test_msgs_msg_Primitives, FIDLPrimitives>(PrimitiveValues, OutData.primitive_values._buffer, PrimitiveValues.Num());
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FIDLDynamicArrayNestedCallback, const FIDLDynamicArrayNested, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSETEST_API UDynamicArrayNested_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FIDLDynamicArrayNestedCallback OnDataChanged;

    virtual void Initialize() override {
        Data = test_msgs_msg_DynamicArrayNested__alloc();
    };

    virtual void Terminate() override {
        test_msgs_msg_DynamicArrayNested_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FIDLDynamicArrayNested& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FIDLDynamicArrayNested Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FIDLDynamicArrayNested NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &test_msgs_msg_DynamicArrayNested_desc;
    };

private:
    test_msgs_msg_DynamicArrayNested* Data;
};