/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPrimitives.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPrimitives.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "DataImplementation/Primitives.h"
#include "Topic/TopicProxy.h"
#include "Utils/MRSConvertUtils.h"

#include "ROSPrimitives.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSPrimitives
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSPrimitives()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    bool BoolValue;
    
    char ByteValue;
    
    unsigned char CharValue;
    
    UPROPERTY(EditAnywhere)
    float Float32Value;
    
    UPROPERTY(EditAnywhere)
    double Float64Value;
    
    char Int8Value;
    
    char Uint8Value;
    
    UPROPERTY(EditAnywhere)
    int16 Int16Value;
    
    UPROPERTY(EditAnywhere)
    uint16 Uint16Value;
    
    UPROPERTY(EditAnywhere)
    int32 Int32Value;
    
    UPROPERTY(EditAnywhere)
    unsigned int Uint32Value;
    
    UPROPERTY(EditAnywhere)
    int64 Int64Value;
    
    UPROPERTY(EditAnywhere)
    uint64 Uint64Value;
    
    UPROPERTY(EditAnywhere)
    FString StringValue;
    

    /**
     * @cond
     */
    void DDSToUE (const test_msgs_msg_Primitives& InData) 
    {
        BoolValue = InData.bool_value;
        ByteValue = InData.byte_value;
        CharValue = InData.char_value;
        Float32Value = InData.float32_value;
        Float64Value = InData.float64_value;
        Int8Value = InData.int8_value;
        Uint8Value = InData.uint8_value;
        Int16Value = InData.int16_value;
        Uint16Value = InData.uint16_value;
        Int32Value = InData.int32_value;
        Uint32Value = InData.uint32_value;
        Int64Value = InData.int64_value;
        Uint64Value = InData.uint64_value;
        UMRSConvertUtils::DDSStringToUE( InData.string_value, StringValue);
    };

    void UEToDDS (test_msgs_msg_Primitives& OutData) 
    {
        OutData.bool_value = BoolValue;
        OutData.byte_value = ByteValue;
        OutData.char_value = CharValue;
        OutData.float32_value = Float32Value;
        OutData.float64_value = Float64Value;
        OutData.int8_value = Int8Value;
        OutData.uint8_value = Uint8Value;
        OutData.int16_value = Int16Value;
        OutData.uint16_value = Uint16Value;
        OutData.int32_value = Int32Value;
        OutData.uint32_value = Uint32Value;
        OutData.int64_value = Int64Value;
        OutData.uint64_value = Uint64Value;
        UMRSConvertUtils::UEStringToDDS(StringValue, OutData.string_value );
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPrimitivesCallback, const FROSPrimitives, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSETEST_API UPrimitives_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSPrimitivesCallback OnDataChanged;

    virtual void Initialize() override {
        Data = test_msgs_msg_Primitives__alloc();
    };

    virtual void Terminate() override {
        test_msgs_msg_Primitives_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPrimitives& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPrimitives Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSPrimitives NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &test_msgs_msg_Primitives_desc;
    };

private:
    test_msgs_msg_Primitives* Data;
};